sudo: false
language: php

cache:
    directories:
        - $HOME/.composer/cache
        - vendor

before_script:
    - mkdir -p build/logs
    - mkdir -p build/cov

before_install:
    - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || echo "xdebug not available"

install:
  - if [[ $deps = 'low' ]]; then
    travis_retry composer update --prefer-dist --no-progress --no-suggest --prefer-stable --prefer-lowest --ansi;
    else
    travis_retry  composer update --prefer-dist --no-progress --no-suggest --ansi;
    fi

script:
    - ./vendor/bin/phpunit -c phpunit.xml.dist

jobs:
    allow_failures:
        - php: nightly
    include:
        - php: '7.2'
        - php: '7.3'
        - php: '7.4'
        - php: '7.4'
        - php: '8.0'
          env: deps=low
        - stage: Metrics and quality
          env: COVERAGE
          before_script:
              - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{.disabled,}
              - if [[ ! $(php -m | grep -si xdebug) ]]; then echo "xdebug required for coverage"; exit 1; fi
              - wget https://phar.phpunit.de/phpcov.phar
              - chmod +x phpcov.phar
              - wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.2.0/php-coveralls.phar
              - chmod +x php-coveralls.phar
          script:
              - ./vendor/bin/phpunit -c phpunit.xml.dist --coverage-php build/cov/coverage.cov
          after_script:
              - phpcov.phar merge --clover build/logs/clover.xml build/cov
              - php-coveralls.phar --no-interaction

        - stage: Metrics and quality
          env: STATIC_ANALYSIS
          script:
              - ./vendor/bin/phpstan analyse

        - stage: Metrics and quality
          env: CODING_STANDARDS
          before_script:
              - wget https://cs.symfony.com/download/php-cs-fixer-v2.phar -O php-cs-fixer
              - chmod a+x php-cs-fixer
          script:
              - ./php-cs-fixer fix --dry-run --stop-on-violation --using-cache=no

        - stage: Security Check
          env: SECURITY_CHECK
          before_script:
              - wget -c https://get.sensiolabs.org/security-checker.phar
              - chmod +x security-checker.phar
          script:
              - ./security-checker.phar security:check
